spring:
  application:
    name: diplom_muzkat
    database: POSTGRESQL
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/diplom
    driverClassName: org.postgresql.Driver
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

