services:
  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=sem7
      - MYSQL_PASSWORD=password
      - MYSQL_ROOR_PASSWORD=password
      - MYSQL_USER=user
    ports:
      -3306:3306