#logging:
#  level:
#    root: debug
http:
  logging:
    enabled: false
    log-level: info

spring:
  application:
    name: book-service
server:
  port: 8181
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
