spring:
  #security:
    #oauth2:
      #resource-server:
        #jwt:
          #issuer-uri: http://localhost:8080/user
  application:
    name: spring-boot-hwsem-7
    issue:
      max-allowed-books: 1
  datasource:
    url: jdbc:h2:mem:hw7db
    driverClassName: org.h2.Driver
    username: kate
    password: kate
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
server:
  port: 8080
management:
  endpoint:
    env:
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include: env, prometheus, health, info, metric
