global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    #  - targets: ['178.205.181.26:8080']
      - targets: ['host.docker.internal:8080']
